version: '3'
services:
  analysis-db:
    image: library/mysql:8.0
    container_name: analysis-db
    restart: always
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: analysis
      MYSQL_USER: cu
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
