spring:
  profiles:
    active: local

logging:
  config: classpath:config/logback-${spring.profiles.active}.xml

management:
  server:
    port: 8182
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info, health
      base-path: /management
  endpoint:
    health:
      showDetails: never
    metrics:
      enabled: true

cache:
  refresh-time-seconds: 3600